### ISSUE TITLE
App becomes unresponsive

### ISSUE THREAD

**Issue by WenSnake** [Cu3PO42/KeySAVe#107]
Have a sav file loaded for checking with options on default and then switch to a custom format.

Custom format is a modified default clone:

**Header:** 

#| Ball |NN| Species (Gender) | Nature | Ability | IVs | HP | Move 1 | Move 2 | Move 3 | Move 4 | Lang. Tag| OT | TID | [Link] |

**Body:**

{{#if (-equal (speciesName) (nickname))}}stuff{{else}}  THINGs {{/if}}?|{{ballImage}} | {{nickname}} | {{speciesName}} {{formName}} ({{genderString gender}}) | {{natureName}} | {{abilityName}} {{#if (hasHa)}}(HA){{else}}{{/if}} | {{ivHp}}.{{ivAtk}}.{{ivDef}}.{{ivSpAtk}}.{{ivSpDef}}.{{ivSpe}} | {{typeName hpType}}| {{moveName move1}} | {{moveName move2}} | {{moveName move3}} | {{moveName move4}} | [{{language}}] | {{ot}} | {{tid}} | [{{esv}}](?) |

The Removal of: "{{#if (-equal (speciesName) (nickname))}}stuff{{else}}  THINGs {{/if}}" allows for normal operation of KeySAVe again.

**Comment by Cu3PO42** [comment]
Right, I was finally able to reproduce yet! Not sure what the issue is, but I'll try to get a minimal reproduction and then get it fixed soon.

**Comment by Cu3PO42** [comment]
The minimal reproduction is:

1. Create a new Handlebars format.
2. Use `{{-equal "foo" "bar"}}` as format string.
3. Open file.
4. Switch to default format.
5. Try to switch format again.
