### ISSUE TITLE
Permit new lines in Handlebar headers

### ISSUE THREAD

**Issue by jasminerae** [Cu3PO42/KeySAVe#108]
Please and thank you!

I'm making a custom reddit template and really need to add that header break back in.

**Comment by Cu3PO42** [comment]
Hi, this is the intended behavior. The headers are interpreted as HTML and as such white lines are stripped out as white space. You can however just insert a `<br />` for a line break :)

**Comment by jasminerae** [comment]
Woo, thanks!
