### ISSUE TITLE
Save Keys on Open File or Application state on exit

### ISSUE THREAD

**Issue by olehermanse** [Cu3PO42/KeySAVe#117]
Every time I open the app I have to go through the steps to break all boxes. Keys should save on "Open File" (?), or the state of the whole app should be saved and reopened.

Have to open KeySAVe, click Open File-> Empty, and Full saves, then click scan folder a couple of times before dumping works correctly without ghosts.

**Comment by Cu3PO42** [comment]
The keys are definitely be supposed to saved. What is your OS and how are you quitting KeySAVe? Please share the log file at `~/.config/keysave.log` if you're on Linux, `%APPDATA%/keysave.log` on Windows or `~/Library/Application Support/keysave.log` on OS X.

**Comment by olehermanse** [comment]
Windows, but I think I was having the same problem earlier on Mac as well.

{"level":"debug","message":"IPC Handler for dump-save-or-bv registered","timestamp":"2016-07-10T11:43:07.026Z"}
{"level":"debug","message":"IPC Handler for break-key registered","timestamp":"2016-07-10T11:43:07.028Z"}
{"level":"debug","message":"IPC Handler for break-folder registered","timestamp":"2016-07-10T11:43:07.029Z"}
{"level":"debug","message":"IPC Handler for merge-key-folder registered","timestamp":"2016-07-10T11:43:07.029Z"}
{"level":"debug","message":"IPC Handler for import-keysav2-folder registered","timestamp":"2016-07-10T11:43:08.284Z"}
{"level":"debug","message":"IPC Handler for search-keysav2 registered","timestamp":"2016-07-10T11:43:08.284Z"}
{"level":"info","message":"KeySAVe - Version 1.2.1 started","timestamp":"2016-07-10T11:43:08.332Z"}
{"level":"info","message":"OS: win32-ia32","timestamp":"2016-07-10T11:43:08.333Z"}
{"level":"debug","message":"IPC Handler for file-dialog-open registered","timestamp":"2016-07-10T11:43:08.339Z"}
{"level":"debug","message":"IPC Handler for file-dialog-save registered","timestamp":"2016-07-10T11:43:08.339Z"}
{"level":"debug","message":"IPC Handler for update-query registered","timestamp":"2016-07-10T11:43:08.340Z"}
{"level":"debug","message":"IPC Handler for update-do registered","timestamp":"2016-07-10T11:43:08.340Z"}
{"level":"info","message":"Dumper process started","timestamp":"2016-07-10T11:43:08.358Z"}
{"level":"verbose","message":"Loading keys from C:\\Users\\olehermanse\\AppData\\Roaming\\KeySAVe/keys","timestamp":"2016-07-10T11:43:08.363Z"}
{"level":"info","message":"Loading config from C:\\Users\\olehermanse\\AppData\\Roaming\\KeySAVe/config.json","timestamp":"2016-07-10T11:43:09.875Z"}
{"level":"info","message":"No update available","timestamp":"2016-07-10T11:43:10.280Z"}
{"level":"verbose","message":"Loading folder C:\\Users\\olehermanse\\Dropbox\\pm\\saves to scan for saves","timestamp":"2016-07-10T11:43:17.645Z"}
{"level":"verbose","message":"Loading folder C:\\Users\\olehermanse\\Dropbox\\pm\\saves to scan for saves","timestamp":"2016-07-10T11:43:23.426Z"}
{"level":"verbose","message":"Loading file C:\\Users\\olehermanse\\Dropbox\\pm\\saves\\2016-07-09_21-46-14.84.sav","timestamp":"2016-07-10T11:43:37.661Z"}
{"level":"verbose","message":"File C:\\Users\\olehermanse\\Dropbox\\pm\\saves\\2016-07-09_21-46-14.84.sav is a save file","timestamp":"2016-07-10T11:43:37.665Z"}
{"level":"info","message":"Saving config","timestamp":"2016-07-10T11:43:54.346Z"}
{"level":"debug","message":"IPC Handler for dump-save-or-bv registered","timestamp":"2016-07-10T11:43:59.584Z"}
{"level":"debug","message":"IPC Handler for break-key registered","timestamp":"2016-07-10T11:43:59.586Z"}
{"level":"debug","message":"IPC Handler for break-folder registered","timestamp":"2016-07-10T11:43:59.586Z"}
{"level":"debug","message":"IPC Handler for merge-key-folder registered","timestamp":"2016-07-10T11:43:59.586Z"}
{"level":"debug","message":"IPC Handler for import-keysav2-folder registered","timestamp":"2016-07-10T11:44:00.810Z"}
{"level":"debug","message":"IPC Handler for search-keysav2 registered","timestamp":"2016-07-10T11:44:00.810Z"}
{"level":"info","message":"KeySAVe - Version 1.2.1 started","timestamp":"2016-07-10T11:44:00.855Z"}
{"level":"info","message":"OS: win32-ia32","timestamp":"2016-07-10T11:44:00.856Z"}
{"level":"debug","message":"IPC Handler for file-dialog-open registered","timestamp":"2016-07-10T11:44:00.863Z"}
{"level":"debug","message":"IPC Handler for file-dialog-save registered","timestamp":"2016-07-10T11:44:00.863Z"}
{"level":"debug","message":"IPC Handler for update-query registered","timestamp":"2016-07-10T11:44:00.863Z"}
{"level":"debug","message":"IPC Handler for update-do registered","timestamp":"2016-07-10T11:44:00.863Z"}
{"level":"info","message":"Dumper process started","timestamp":"2016-07-10T11:44:00.878Z"}
{"level":"verbose","message":"Loading keys from C:\\Users\\olehermanse\\AppData\\Roaming\\KeySAVe/keys","timestamp":"2016-07-10T11:44:00.882Z"}
{"level":"info","message":"Loading config from C:\\Users\\olehermanse\\AppData\\Roaming\\KeySAVe/config.json","timestamp":"2016-07-10T11:44:02.318Z"}
{"level":"info","message":"No update available","timestamp":"2016-07-10T11:44:02.642Z"}
{"level":"verbose","message":"Loading file C:\\Users\\olehermanse\\Dropbox\\pm\\saves\\2016-07-09_21-46-14.84.sav","timestamp":"2016-07-10T11:44:17.722Z"}
{"level":"verbose","message":"File C:\\Users\\olehermanse\\Dropbox\\pm\\saves\\2016-07-09_21-46-14.84.sav is a save file","timestamp":"2016-07-10T11:44:17.754Z"}
{"level":"info","message":"Saving config","timestamp":"2016-07-10T11:44:25.286Z"}
{"level":"info","message":"Shutting down dumper process","timestamp":"2016-07-10T11:44:25.304Z"}

**Comment by olehermanse** [comment]
Quitting with top right X or alt+f4, makes no difference. Tried running as admin, makes no difference.

**Comment by Cu3PO42** [comment]
The log file looks good. I just checked on OS X and Windows and don't have an issue on either. Can you check if the key files are modified when you quit KeySAVe, please? They are stored in `%APPDATA%/keysave/keys`.

**Comment by olehermanse** [comment]
They are definitely not updated. Date Modified and Created is the same. (Initial breaking)

**Comment by Cu3PO42** [comment]
Could you please double check if you are experiencing the same issues on OS X? I can't seem to reproduce this issue right now.

**Comment by olehermanse** [comment]
Yes, I checked now and my mac installation seems to work flawlessly on the same save files.

**Comment by Cu3PO42** [comment]
Yay. Platform specific behavior on cross-platform libraries. For the record, which version of Windows are you running?
