### ISSUE TITLE
Use shiny picture for other game TSV matches.

### ISSUE THREAD

**Issue by shadowofdarkness** [Cu3PO42/KeySAVe#122]
When using the pretty formatting can you make it so any shiny matches from the "any of these SVs" use the shiny picture not just ones that match the current save.

It would help me allot since I have a list of along fifteen TSVs I check for myself and others and sometimes it can be hard to realize if a hit is because it matches my filter criteria or is a shiny override because I can't remember all the SVs I have saved to notice at a glance.

**Comment by Cu3PO42** [comment]
Thanks for the suggestion! This is definitely something that I will be adding soon :)
