### ISSUE TITLE
Remember last opened file type

### ISSUE THREAD

**Issue by Cu3PO42** [Cu3PO42/KeySAVe#135]
Remember the type of the last opened file and automatically select the corresponding filter on the next dialog.

**Comment by Bobblybook** [comment]
Further to this, could you possibly implement a "reload file" button? I find I am continuously loading the same file over and over, would be convenient to be able to reload it without having to reselect the path.

**Comment by Cu3PO42** [comment]
Since there is no way to achieve the desired results in all webbrowsers (or all platforms) the current behaviour is going to stay I'm afraid.
