### ISSUE TITLE
Can't copy output to clipboard with Reddit formatting

### ISSUE THREAD

**Issue by Droidem** [Cu3PO42/KeySAVe#139]
It does not work on 1.3.0.

**Comment by Cu3PO42** [comment]
Works fine for me. Are you possibly using any clipboard 'enhancing' programs that might cause a problem?

**Comment by Droidem** [comment]
none that I could think of. Unless one got installed without me knowing.

**Comment by Cu3PO42** [comment]
The generation of plain text for the Reddit formatting throws an exception, which is why this happens. This should be easy to fix :)
