### ISSUE TITLE
Save output as file

### ISSUE THREAD

**Issue by Droidem** [Cu3PO42/KeySAVe#140]
It does not work. "Couldn't save file. Please try again." 

version 1.3.0

**Comment by Cu3PO42** [comment]
I cannot reproduce this issue, it works fine for me. What OS are you using? Can you confirm KeySAVe has permissions to write at the path you chose?

**Comment by Droidem** [comment]
Windows 10. And it's on my second drive, which KeySAVe is also installed on.

**Comment by Cu3PO42** [comment]
Right, so this is the exact same issue as #139, so I'll merge it with that one.
