### ISSUE TITLE
Powersaves backups of physical carts don't work

### ISSUE THREAD

**Issue by rmac5** [Cu3PO42/KeySAVe#144]
After following directions [here](https://cu3po42.gitbooks.io/keysave/content/dumping/saves.html#ghosts) under Initial decryption, I get the following message. I have tried this using other pokemon too.

""The two save files are not from the same game and cannot be used together to create a key.
Please follow the instructions.""

EDIT:  I tried it again using 6 different pokemon and got this message:

"Could not find your boxes in the save file. This error occurs if you did not follow the instructions or are using an unsupported game. Please follow the instructions."

**Comment by Cu3PO42** [comment]
It appears that this error is specific to Powersaves backups of generation 7 games. I am currently investigating the issue.

**Comment by Cu3PO42** [comment]
It'd be a great help if everyone encountering this issue could send me their save files so I can make sure I fix as many cases as possible.

**Comment by gentlerain** [comment]
just sent you my save files :)! Good luck and thank you!

**Comment by Cu3PO42** [comment]
As of right now I've hit a bit of a wall with this. It looks like either of this is happening:

1. Powersaves does weird stuff with the saves for whatever reason.
2. The game uses encryption on the Pokémon that is not One Time Pad.
3. A changing xorpad is used.

**Comment by Cu3PO42** [comment]
Sun and Moon are CARD1 games, whereas XY and ORAS were CARD2 games. This means that save data is stored on a separate save chip, where wear leveling is employed. Subsequently we'd need the blockmap to make any kind of sense of the data, however that is encrypted as well, so we can't read it without generating the XORpad on a 3DS. If you can do that however, you can also use a save manager and extract the decrypted save.
So it doesn't make a whole lot of sense to do that.

**TL;DR** SuMo have different save chips that are not directly vulnerable to the same flaw in encryption as XY and ORAS and won't work for the foreseeable future.
