### ISSUE TITLE
Alolan form hidden abilities not recognized by hasHa

### ISSUE THREAD

**Issue by RhinoKneel** [Cu3PO42/KeySAVe#151]
Currently have an Alolan Rattata and Vulpix with their form's hidden ability, but not being recognized as hidden abilities by hasHa. Possible the abilities are in extended slot numbers from the original Pokemon.

**Comment by Cu3PO42** [comment]
@RhinoKneel why did you close this? Wasn't it actually an issue?

**Comment by RhinoKneel** [comment]
Figured out later my handlebar formatting was why it wasn't showing up. 
When I caught a non-Alolan HA and still nothing, I realized hasHA couldn't be used with #if or checkmark directly to give notice of a hidden ability. I would need it to read TRUE or FALSE and react from that.

**Comment by Cu3PO42** [comment]
@RhinoKneel You can use it with `{{#if}}`, however helpers have to be put in brackets!

```hbs
{{#if (hasHa)}}
    stuff
{{/if}}
```
