### ISSUE TITLE
Pokemon max IV being incorrectly highlighted red

### ISSUE THREAD

**Issue by Bobblybook** [Cu3PO42/KeySAVe#153]
After breeding many boxes of a pokemon, one specific one keeps showing an IV of 31 highlighted red in the "Pretty" format (as if it's an IV of 0 or 1).
I have checked ingame, and it does infact have an IV of 31 in that stat, so I'm not sure why it's being highlighted.

Attached my save file, the suspect pokemon is at the end of the list, Box 12, slot 1,2.

[main.zip](https://github.com/Cu3PO42/KeySAVe/files/614625/main.zip)

**Comment by Cu3PO42** [comment]
This is actually working as intended. If your Pokémon has a -Spe nature, high IVs will be red and low IVs will be green with regard to Trick Room sets.
