### ISSUE TITLE
Allow reading full 32 gen 7 boxes from ram dump files.

### ISSUE THREAD

**Issue by shadowofdarkness** [Cu3PO42/KeySAVe#158]
Even back in gen 6 I have been re-purposing the old obsolete RAM pcdata.bin files to still be useful by creating them using NTR debugger which allows me to check eggs without leaving the game and copying save files to the computer.
This works great and even works in Sun & Moon. With the only problem being that due to your check on the file it is limited to the old size which only covers 31 boxes, could you allow for bigger files to account for box 32.

This is a great and easy way to check and if I go long enough without good results due to no forced saves I can reset without saving to purge eggs. All I do is collect some eggs then hit the home button to suspend the game and have the system connect to Wi-Fi, dump pcdata.bin with NTR then home button to resume the game. It's a easy 10 seconds to check a batch of eggs.

**Comment by shadowofdarkness** [comment]
I'm still having problems and can't read a full 32 box dump. If I load one the correct size the box range selector now includes 32 but no Pokemon show at all from any box. Loading a 31 box size file still works but only shows 31 boxes of course.

Working file made with (for size I used 232*30*31 in hex)
data(0x330d9838, 0x34ad0, filename='pcdata.bin', pid=0x3e)

When I increase it to 232*30*32 in hex KeySAVe can't open it correctly but at least doesn't give errors like before
data(0x330d9838, 0x36600, filename='pcdata.bin', pid=0x3e)

Offset only tested in Moon but is probably the same for Sun

**Comment by Cu3PO42** [comment]
Can you please share the file with me so I can test this? I don't have access to a system where I could create one myself, unfortunately.

**Comment by shadowofdarkness** [comment]
I have emailed you the some example files one a full 32 dump and one smaller 31 that works.

Also note that if truncated to the smaller size the 32 starts working just missing the last box.

These files are from my quick play through save for extra legends so it doesn't have much just enough to spread around to unlock all the boxes. But does have a Pokemon in box 32 that should show up.
