### ISSUE TITLE
Endless Spinning Blue Circle

### ISSUE THREAD

**Issue by skurpy** [Cu3PO42/KeySAVe#160]
I was doing the Initial break to check ESVs in Pokemon Sun, I accidentally clicked on "Search for KeySAV2 installations" now I've had a blue circle running on my break screen.  I tried closing and even uninstalling but when I return to the break tab I still have the spinning circle, I've left my pc like that for about 4 hours now, still nothing. Sorry about the long post and also if this is something others have experienced feel free to link the solution I couldn't find one.

**Comment by skurpy** [comment]
Finally found something on reddit nevermind lol

**Comment by Cu3PO42** [comment]
Do you mind letting me know what you found? If there is a bug I'd like to avoid it in the future.

**Comment by skurpy** [comment]
I couldn't find what caused the problem, but this is the reddit thread I found 

https://www.reddit.com/r/SVExchange/comments/5dwmyv/question_about_keysave_issue/

I ended up following the end, opening the cmd prompt and copying the command he wrote to clear the config. Sorry I'm not more help I'm not great with tech but KeySAVe is a great software thank you so much for putting the time in to make it.

**Comment by Cu3PO42** [comment]
Ah yes. I thought I fixed this in the last update, but might a tiny, but fatal mistake, so it wasn't actually fixed.

It will be properly fixed in the next update.
