### ISSUE TITLE
Difficulty Breaking Boxes

### ISSUE THREAD

**Issue by bladeddarkness** [Cu3PO42/KeySAVe#161]
I'm using a digital copy of Moon. I managed to break the key and get my TSV, but I cannot get it to break my boxes. I followed the instructions on Dumping - Saves page, I believe.
What I get, when I check the Dumping tab on KeySAVe, is 4 slots - 3 of which are ghosts.
~B1 - 5,1
~B2 - 3,6
B5 - 1,1
~B6 - 1,6
I'm wondering if this is an issue with my key not breaking properly, but I'm unsure how to check this - it always tells me there's no need because I already have a key. I've tried quite a few .sav files, moving the Pokemon and the empty boxes around in various ways.

**Comment by Cu3PO42** [comment]
This seems strange. If KeySAVe detects that a key slot isn't working properly it should clear it and start over. Can you send me the save files you used so I can reproduce the issue?

**Comment by bladeddarkness** [comment]
I can do that. I'll email them to you right now.

I'm still not sure how the slot in Box 5 opened. I didn't have anything in it at the time nor was I trying to break it. I've dumped some more save files since then, and it did unlock a few slots, but they seemed random and usually were not even the ones I was trying for. Trying to unlock a bunch either results in the KeySAVe not even noticing there's been a change, a ghost, or a random unlock.

**Comment by Cu3PO42** [comment]
I'm sorry I couldn't get back to you earlier. Life's been quite busy. I am looking into this right now and quite frankly the behavior I'm seeing is just super weird.

Is the language of you save file Japanese? Can you also send over other files you've tried so I have some more data to work with?

**Comment by Cu3PO42** [comment]
In fact, it appears I have faced a similar issue before and wasn't able to resolve it at the time. It manifests itself through a OT language ID that is way out of the valid range.

**Comment by bladeddarkness** [comment]
No worries, I've been super busy as well. I'll email you the last few saves from when I was really trying to get it to work.

It should be in English unless something incredibly bizarre happened. I've been playing in English anyways, and the OT is Lilith.

**Comment by Cu3PO42** [comment]
After further investigation I still have no idea what is going on and have not been able to reproduce it with any other game. I am not sure this is on the KeySAV anymore rather than something funky going on with your console/game.

If you have experienced this bug with another game/system or know of someone else, please let me know, but for now I'm going to close, I'm afraid.
