### ISSUE TITLE
Issue breaking for the first time

### ISSUE THREAD

**Issue by Atwolf** [Cu3PO42/KeySAVe#163]
I'm using Powersaves, and I've been backing the game up and following the steps to the letter as found here: https://cu3po42.gitbooks.io/keysave/content/dumping/encrypted-saves.html .However, when I press break, I am getting different errors - sometimes keysave tells me the two save files are from different games, other times it says it can't find my boxes. I have tries this over and over again... please help.

EDIT: I realized it isn't supposed to work for Gen 7 as of late. Any estimate for how long it'll take to work?

**Comment by Cu3PO42** [comment]
Physical copies of Generation 7 games cannot be supported until full save decryption is possible on a PC, for this we need a Bootrom dump to be released so the required keys can be extracted. You can find a more detailed explanation in #144.
