### ISSUE TITLE
Some boxes are not shown when splitting boxes is active

### ISSUE THREAD

**Issue by Droidem** [Cu3PO42/KeySAVe#164]
When the option with Split Boxes is checked, it stops at Box 17 even if there is more pokemon in boxes after it. Uncheck it and the other boxes are viewed.

**Comment by Cu3PO42** [comment]
Every formatter has completely different code, so the issue would likely just exist in one of them? Can you tell me which?

**Comment by Droidem** [comment]
So I just verified with a save that has random pokemon in random boxes and it goes past box 17 now. This might have been a save file or just no longer an issue? not sure. But I don't have a reason to have this open still.

**Comment by Cu3PO42** [comment]
I have managed to reproduce it. It's not specific to box 17, but depends on the sequence of boxes containing Pokémon.
