### ISSUE TITLE
Chinese Characters do not show up. (Simplified and Traditional) 

### ISSUE THREAD

**Issue by WenSnake** [Cu3PO42/KeySAVe#171]
 show up instead for CHS and CHT Pokémon names. Korean and Japanese characters show up fine. Copying and pasting still only shows .

KeySAVe Version 1.4.0 on Windows and I was using a NA digital English language Moon game

**Comment by Cu3PO42** [comment]
It appears to work just fine on macOS. What version of Windows are you using and do you have the required fonts installed?

**Comment by Cu3PO42** [comment]
It is confirmed working on multiple Windows 10 installations.

**Comment by WenSnake** [comment]
Hmm I have Windows 10 and installed the fonts, but I still don't see the characters. Maybe I have the wrong fonts installed?

**Comment by Cu3PO42** [comment]
Well, this is odd. You are talking about the nicknames, right? Do you see any Chinese characters for Species, Nature, etc. when you set the language to Chinese?

**Comment by WenSnake** [comment]
When I switch it to Chinese, it does indeed show Chinese characters for Species, Nature, etc, but the "nickname" are still in blocks.

**Comment by Cu3PO42** [comment]
Weird. Can you send me the save (+ key if applicable) so I can look into it?

**Comment by WenSnake** [comment]
Not entirely sure where the keys are located for KeySAVe, but I can send a save.

**Comment by Cu3PO42** [comment]
If it's a main file that would suffice. If it's not, the keys are in `%APPDATA%/keysave/keys`.

**Comment by Cu3PO42** [comment]
I can reproduce the issue now, but I don't know what's causing it yet.

**Comment by Cu3PO42** [comment]
I have figured out the problem. Apparently Nintendo didn't just use Unicode like they did for Japanese and Korean, but have defined their own codepoints.

**Comment by WenSnake** [comment]
Oh great, was having trouble figuring which key was used for my save, since none looked right or I wend down the wrong path.

**Comment by Cu3PO42** [comment]
Yeah, the names are just base64 encoded byte sequences that identify your save... You could just have sent me all keys though ;)

**Comment by WenSnake** [comment]
Oh I was looking at an old folder with KeySAV2 keys and they appeared to be auto-named. "SAV Key - Wen - (64359.36557) - TSV 1882", is it possible for KeySAVe keys to be auto-named the same way? I can open up an issue if it's an agreeable change.

**Comment by Cu3PO42** [comment]
They used to be called this in KeySAVe as well, but "it's not a bug it's a feature". Having the stamp in the name allows me to index them without actually loading them all, which reduces memory usage and startup delay for people with large amounts of keys.

It also caused some confusion for users since the key remains valid when a game is restarted on a cartridge, but the OT information changes obviously.

**Comment by WenSnake** [comment]
Hmm, I guess the only other thing I can think of is tossing on the game version, but most people won't bother with the keys anyway.
