### ISSUE TITLE
SHELL32.dll not finding getcurrentprocessexplicitAppUserModelID

### ISSUE THREAD

**Issue by mcdrill89** [Cu3PO42/KeySAVe#174]
I had to downgrade to an old dell desktop after two other computers suffered hardware issues to the motherboard and CPU but now when I launch Key save I get this error message. Any work
![keysaverror](https://user-images.githubusercontent.com/3318921/27593465-418979c0-5b25-11e7-81ea-ffaca050b30f.jpg)

rounds or am I just not using the right version of KeySAVe

**Comment by Cu3PO42** [comment]
This looks like you might be running Windows Vista.

Unfortunately the underlying technology (Electron) only runs on Windows 7 or newer. Should you be using Windows 7, I will look into it further, otherwise I'm afraid I can't help you other than suggest running a different OS.

**Comment by Cu3PO42** [comment]
Closing for now. Should you in fact be using Windows 7, I will happily reopen this issue.
