### ISSUE TITLE
Problem to break my file .sav

### ISSUE THREAD

**Issue by Triple89S** [Cu3PO42/KeySAVe#179]
Hi, I'm tryin' to break my box since three days, but every time I try to do it the tool tell me "The two save files are not from the same game and cannot be used together to create a key. Please follow the instructions."
How can I solve this problem?
Please **HELP ME**

**Comment by Cu3PO42** [comment]
Hi,

first of all, contacting me three times within 8 minutes won't make me help you any faster.
Please just come here when you need help in the future.

You are saying you have Pokémon Sun. Are you using digital saves? Powersaves is not supported with SuMo at this time.

**Comment by Triple89S** [comment]
Thank you and excuse me if I just look insisting, but in three days I’ve lost a lot if time. I got the retail version, not The digital one. I’m using the PowerSaves yet, how can I do without it?
Thank you very much



Inviato da myMail per iOS


domenica 31 dicembre 2017, 17:16 +0100 da notifications@github.com <notifications@github.com>:

Hi,

first of all, contacting me three times within 8 minutes won't make me help you any faster.
Please just come here when you need help in the future.

You are saying you have Pokémon Sun. Are you using digital saves? Powersaves is not supported with SuMo at this time.

**Comment by Cu3PO42** [comment]
I do appreciate that you tried to solve the problem first, but if you're stuck, you can ask.
In general I do recommend (and ask) that you consult the [documentation](https://cu3po42.gitbooks.io/keysave/content/). It clearly states that your current scenario is not supported.

You can find all supported breaking methods there as well. In your case you could use Battle Videos (not very comfortable to use) or Homebrew.

**Comment by Triple89S** [comment]
If I understand well, homebrew is a sort of hacking My 3DS and I don’t like it very much. If I want to use the battle video method, it’s one time only and I got the key to break the box? (Excuse My terrible english)



Inviato da myMail per iOS


domenica 31 dicembre 2017, 17:26 +0100 da notifications@github.com <notifications@github.com>:

I do appreciate that you tried to solve the problem first, but if you're stuck, you can ask.
In general I do recommend (and ask) that you consult the documentation<https://cu3po42.gitbooks.io/keysave/content/>. It clearly states that your current scenario is not supported.

You can find all supported breaking methods there as well. In your case you could use Battle Videos (not very comfortable to use) or Homebrew.

**Comment by Cu3PO42** [comment]
Yes, Homebrew is a kind of "hacking", however the risks are quite minimal.
Using the Battle Video method you cannot break your boxes. You can only check Pokémon that you use in battle. You can find the details in the documentation.

**Comment by Triple89S** [comment]
So the only method avalaible is The HB?
The KeySave work for UltraMoon or is The same?



Inviato da myMail per iOS


domenica 31 dicembre 2017, 17:38 +0100 da notifications@github.com <notifications@github.com>:

Yes, Homebrew is a kind of "hacking", however the risks are quite minimal.
Using the Battle Video method you cannot break your boxes. You can only check Pokémon that you use in battle. You can find the details in the documentation.

**Comment by Cu3PO42** [comment]
Yes, Homebrew is the only available method that is user friendly and will work with your current game.
Alternatively you can buy a digital copy of the game.

The same restrictions apply to USUM.

**Comment by Triple89S** [comment]
Do you have a tutorial for The HB? I need an R4? Because my 3DS is at The latest version...



Inviato da myMail per iOS


domenica 31 dicembre 2017, 17:43 +0100 da notifications@github.com <notifications@github.com>:

Yes, Homebrew is the only available method that is user friendly and will work with your current game.
Alternatively you can buy a digital copy of the game.

The same restrictions apply to USUM.

**Comment by Cu3PO42** [comment]
All relevant resources for getting access to Homebrew that I am aware of can be found in the documentation.

**Comment by Triple89S** [comment]
Thank you so much!



Inviato da myMail per iOS


domenica 31 dicembre 2017, 17:49 +0100 da notifications@github.com <notifications@github.com>:

All relevant resources for getting access to Homebrew that I am aware of can be found in the documentation.
