### ISSUE TITLE
A Javascript error occurred in the main process 

### ISSUE THREAD

**Issue by NitroNick-exe** [Cu3PO42/KeySAVe#196]
Whenever I try to open KeySAVe I am greeted with this error message what exactly am I doing wrong? 
![KeySAVe_VwOze43pK3](https://user-images.githubusercontent.com/68208220/95665135-002a7a00-0b13-11eb-8080-8a84c56fde48.png)

**Comment by NitroNick-exe** [comment]
I had forgotten I hadn't installed nodejs

**Comment by Cu3PO42** [comment]
You shouldn't need to install Node.js manually to use KeySAVe, it ships with its own. But it fixed the error for you?
