### ISSUE TITLE
Selectively disable Cut/Copy/Paste menu

### ISSUE THREAD

**Issue by Cu3PO42** [Cu3PO42/KeySAVe#48]
Due to #31 such a menu was added. The options should only be enabled when they are actually sensible.

**Comment by bulldog98** [comment]
Does this mean only on OS X?

**Comment by Cu3PO42** [comment]
The reason this issue was marked for OS X is that at the time of creation, Linux and Windows did not have a menu bar at all and as such no items that could be enabled or disabled.

**Comment by Cu3PO42** [comment]
Ideally all text, but dumping output and the input fields should also be made unselectable.

**Comment by Cu3PO42** [comment]
Since the project is now moving to a web application, this is no longer relevant.
