### ISSUE TITLE
Issue with windows pinning on taskbar

### ISSUE THREAD

**Issue by Beardandfeared** [Cu3PO42/KeySAVe#66]
When KeySavE is pinned to task bar, and opened from there it opens another instance of the program, not the pinned one.
https://gyazo.com/66b81f3049ca4f8f9f7eb217be948f14
Windows 10.

**Comment by Cu3PO42** [comment]
If you consider being able to have two instances of the app open a bug, it is not. I don't see why it should be. If you are referring to having two instances on the task bar, I cannot reproduce that and apparently it is a  Windows 10 bug. Please update.
