### ISSUE TITLE
Symbols do not show up in Trainer Names or Nicknames

### ISSUE THREAD

**Issue by WenSnake** [Cu3PO42/KeySAVe#67]
I gave a Pokémon a nickname of all symbols as a test and it does not show up on KeySAVe. Specially it was given ♥♠♦♣★♪☂☁☼☃ .

For Trainer name I only have a Pokémon with an OT with ♥'s in it to verify that it does not show up on KeySAVe.

I assume most of the symbols on the symbols page of the naming screen does not show up.

**Comment by Cu3PO42** [comment]
So Nintendo helpfully defined their own code points for these symbols in a private use area. I will need a decoding table.

**Comment by Cu3PO42** [comment]
See Cu3PO42/KeySAVCoreJS#8
