### ISSUE TITLE
Forms are wrong, seems to be an off by one problem

### ISSUE THREAD

**Issue by WenSnake** [Cu3PO42/KeySAVe#86]
ninjaspidermonkey noticed it first.

{{formName}} has Unowns off by one. Unown B is listed as A, Unown C is listed as B, etc. Unown A doesn't list a form.

Same issue with Vivillon patterns. Icy Snow isn't list as a form. All patterns are wrong from a glance.

Contact me in chat if you want the exact mismatch for Vivillon patterns.

**Comment by WenSnake** [comment]
Form: Incorrect Form Given

Vivillon patterns:

Archipelago:    Marine
Continental:    Tundra
Elegant:          Garden
Garden:          Continental
High Plains:    Archipelago

Icy Snow:       [n/a]
Jungle:          Ocean
Marine:          Modern
Meadow:       Elegant 
Modern:        Meadow

Moonsoon:  River
Ocean:        Sun
Polar:          Icy Snow
River:          Sandstorm
Sandstorm: High Plains

Savanna:   Moonsoon
Sun:           Savanna
Tundra:      Polar
Poké Ball:  Fancy
Fancy:       Jungle
--------------------------

Flabébé:

Red: [n/a]
Blue: Orange
Yellow: Red
Orange: Yellow
White: Blue

**Comment by Cu3PO42** [comment]
Thanks a ton WenSnake, this helps so much!
