### ISSUE TITLE
Formatting information doesn't update when you change from a default option to a non-default option or delete an option

### ISSUE THREAD

**Issue by YaManicKill** [Cu3PO42/KeySAVe#87]
Reproduction steps:

* Go to formatting editing.
* Go to CSV. 
* Clone CSV. 
* Go to a different formatting option (TSV for example). Everything works.
* Go back to the clone of CSV. It doesn't update everything, it keeps the formatting of the TSV one.

Note that if you check "split boxes" when it has not updated information, it will then update immediately. Seems like a binding issue of some sort, possibly.

**Comment by Cu3PO42** [comment]
Seems there are some cases when this is still broken.
