### ISSUE TITLE
Allow direct input on box filter

### ISSUE THREAD

**Issue by brickmaster32000** [Cu3PO42/KeySAVe#88]
Only being able to adjust the range of the boxes shown with sliders makes it difficult to zero in on specific boxes.

**Comment by Cu3PO42** [comment]
I might replace them by simple drop downs. Other suggestions?

**Comment by brickmaster32000** [comment]
If there is a way to limit it so when you push one slider past the other it stops instead of readjusting both of them that could also help greatly if you still want to keep the aesthetics the sliders provide.
