### ISSUE TITLE
Custom TSV feild only works with first TSV

### ISSUE THREAD

**Issue by brickmaster32000** [Cu3PO42/KeySAVe#93]
When typing TSVs into the "any of these SV's" field only the first TSV seems to get checked. I have tried typing in the TSVs separated be spaces and commas and neither seems to make a difference.

**Comment by Cu3PO42** [comment]
Thanks for reporting this, the issue is actually that the second is parsed base 2, the third base 3, etc. I already fixed this in #876356336a1ebf05e96b7067b20c704f5f6cd36c, a new release is probably going up today.
