### ISSUE TITLE
Cannot Dump Single Box

### ISSUE THREAD

**Issue by Sushiimi** [Cu3PO42/KeySAVe#98]
When trying to dump data from a single box (marked 1-1 or any other box number under the "Open File" parameter), program shows the desired box and the one following it (select 1-1 and you receive Box 1 and Box 2).

**Comment by Cu3PO42** [comment]
Thanks for reporting! I'll fix this in the next update. Unfortunately the updater is currently broken, so you'll need to update manually.

**Comment by Sushiimi** [comment]
No problem! Glad I could help out.
